# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160101171725 on 2016-01-02 14:53
from __future__ import unicode_literals

from django.db import connection, migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelegatedWithDBDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.DateTimeField(delegate=True, delegate_on_insert=True, delegate_on_update=True, return_on_insert=True, return_on_update=True)),
                ('num', models.IntegerField(return_on_insert=True, return_on_update=True)),
                ('num_a', models.IntegerField(return_on_insert=True)),
                ('num_b', models.IntegerField(return_on_update=True)),
                ('b', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlyDelegatedFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(delegate=True, delegate_on_insert=True, delegate_on_update=True, null=True, return_on_insert=True, return_on_update=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartiallyDelegated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert', models.IntegerField(delegate_on_insert=True, null=True, return_on_insert=True)),
                ('update', models.IntegerField(delegate_on_update=True, null=True, return_on_update=True)),
                ('both', models.IntegerField(delegate=True, delegate_on_insert=True, delegate_on_update=True, null=True, return_on_insert=True, return_on_update=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithDelegatedFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(delegate=True, delegate_on_insert=True, delegate_on_update=True, null=True, return_on_insert=True, return_on_update=True)),
                ('b', models.TextField(null=True)),
            ],
        ),
    ]



if connection.vendor == 'postgresql':
    Migration.operations.append(
        migrations.RunSQL(
            """
            ALTER TABLE delegated_fields_delegatedwithdbdefault ALTER COLUMN now SET DEFAULT CURRENT_TIMESTAMP;

            CREATE FUNCTION set_num()
            RETURNS trigger AS '
                BEGIN
                    IF NEW.num IS NULL THEN
                        NEW.num = 0;
                    ELSE
                        NEW.num := NEW.num + NEW.num;
                    END IF;
                    NEW.num_a = 1;
                    NEW.num_b = 1;
                    return NEW;
                END'
            LANGUAGE 'plpgsql';

            CREATE TRIGGER auto_set_num
            BEFORE UPDATE OR INSERT ON delegated_fields_delegatedwithdbdefault
            FOR EACH ROW
            EXECUTE PROCEDURE set_num();
            """
        )
    )
